apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-store-deployment
  labels:
    app: book-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-store
  template:
    metadata:
      labels:
        app: book-store
    spec:
      containers:
        - name: book-store
          image: dockerimageregistory.azurecr.io/onlinebookstore/bookstore:latest
          ports:
            - containerPort: 8080