apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: book-store-deployment
  name: book-store-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: book-store-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: book-store-deployment
    spec:
      containers:
        - image: dockerimageregistory.azurecr.io/onlinebookstore/bookstore:latest
          imagePullPolicy: Always
          name: bookstore
      restartPolicy: Always